spring.application.name=raizes-api
spring.datasource.url=jdbc:mysql://localhost:3306/raizesdb
spring.datasource.username=root
spring.datasource.password=victor.mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
